# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jailandrade's site
email: jailandrade@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I love writting stuff for the web and computers, sometimes code, sometimes prose.
  I am working on making better websites and web systems. I specialize in working with HTML5, CSS3, JavaScript and Node.js
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jailandrade.github.io" # the base hostname & protocol for your site
twitter_username: jailandrade
github_username:  jailandrade

# Build settings
markdown: kramdown
